### ISSUE TITLE
Parameter automation appears to be broken in Live

### ISSUE THREAD

**Issue by SidLipovits** [ffAudio/Frequalizer#1]
Fun plug, but trying to automate parameters in Live fails for some reason.

BTW - built with 9th March 2018 dev branch of Juce.

**Comment by ffAudio** [comment]
Cool, thanks for the feedback. Did you compile yourself or did you download the package?
Also, did you use AU or VST?
Thanks, I will try to get hold of a Live version to debug.

**Comment by SidLipovits** [comment]
Built myself starting with the JUCE project you had.  Worked fine in Logic.

Thank you for making this Daniel.

**Comment by ffAudio** [comment]
Great, thanks for the additional info.
I just found this thread on the forum:
https://forum.juce.com/t/automation-not-working-in-ableton-and-studio-one-with-gui-open/22256
Even though I think I don't spam the automation, this might be a lead to check. Unfortunately I won't have time the next few days... If you find something let me know...
Cheers!

**Comment by SidLipovits** [comment]
I took a few minutes and made an example of what i am seeing, then posted to the JUCE forum here -> https://forum.juce.com/t/parameter-automation-audioprocessorvaluetreestate-and-live/

Hopefully, it is something simple that I overlooked.

**Comment by ffAudio** [comment]
So it is a verified JUCE issue, I am keeping an eye on it, should be sorted soon...
