### ISSUE TITLE
Analyser not ready when FrequalizerAudioProcessorEditor::paint is called

### ISSUE THREAD

**Issue by jpanneton** [ffAudio/Frequalizer#4]
When I run it (using the latest JUCE 5.4.1 build in Visual Studio), it crashes in FrequalizerAudioProcessorEditor::paint, see this stacktrace:
![fe5bde6089db1b5e0a855790b7b300518e802592](https://user-images.githubusercontent.com/15305700/50039710-90293680-0004-11e9-9f2b-08dcd33657c5.png)
It crashes because inputAnalyser and outputAnalyser in FrequalizerProcessor.cpp have no channels yet. In fact, the channels are only initialized when calling setupAnalyser in FrequalizerAudioProcessor::prepareToPlay. However, it seems like the paint method is called before this happens, and the paint method doesn’t seem to be called multiple times. To fix it, I preset the size of the averager in the constructor of Analyser. Just like so:
![image 6](https://user-images.githubusercontent.com/15305700/50039806-bd76e400-0006-11e9-8086-985d5d869b24.png)
Then, it works just fine.

**Comment by ffAudio** [comment]
I thought I pushed a fix, but seems I missed to commit the Analyser.h file.
However, I think I like your idea better to initialise it in the constructor already, since all information is present already at that point.

**Comment by ffAudio** [comment]
This should be fixed with 510d834f69cd4b1ccfd6aeec4ae43750a5591f85

Thanks @jpanneton for the report and the suggestion
