### ISSUE TITLE
FFAudioData not defined？

### ISSUE THREAD

**Issue by thewintersun** [ffAudio/Frequalizer#8]
FFAudioData not defined？

**Comment by ffAudio** [comment]
Thanks for the heads up, that was changed when migrating to the CMake build.
I will have to rename it back to the generic BinaryData namespace.

**Comment by ffAudio** [comment]
I double checked, and it compiles here as well as on the github workflows.
I used FFAudioData as namespace instead of BinaryData.

Can you tell a bit more what you did to get that error?

**Comment by ffAudio** [comment]
Closing since not reproducible.
